[versions]
android-compileSdk = "36"
android-minSdk = "33"
android-targetSdk = "36"

# Core
agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.3"

# Lifecyle & Compose
androidx-activity = "1.12.2"
androidx-lifecycle = "2.9.6"
compose-hotReload = "1.0.0"
compose-multiplatform = "1.9.3"

# Navigation3
compose-navigation3 = "1.0.0-alpha06"
lifecycle-viewmodel-navigation3 = "2.10.0-alpha07"

# Room
room-version = "2.8.4"
sqlite-version = "2.6.2"

# Datastore (SharedPreferences)
datastore-version = "1.2.0"

# Koin
koin-version = "4.2.0-beta2"

# Serialization-Json
serialization-json = "1.9.0"

# Coroutines
kotlinx-coroutines = "1.10.2"

# Coil
coil-version = "3.3.0"

# Ktor Client
ktor-version = "3.3.3"

# Ktor Server
ktor-logback = "1.5.23"
ktor-postgres-sql-driver = "42.7.8"
ktor-hikari-cp = "7.0.2"
ktor-exposed-orm = "0.61.0"
ktor-server-auth = "3.3.3"

# Testing
junit = "4.13.2"
androidx-espresso = "3.7.0"
androidx-testExt = "1.3.0"
mockk = "1.14.7"

# Bcrypt Hashing
bcrypt = "0.10.2"

[libraries]

# Lifecyle & Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# ViewModels
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

# Room
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite-version" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-version" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-version" }
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room-version" }

# Datastore
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore-version" }
androidx-datastore-preferences = {module = "androidx.datastore:datastore-preferences", version.ref = "datastore-version"}

# Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil-version" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil-version" }

# Navigation3
compose-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "compose-navigation3" }
compose-lifecycle-viewmodel-nav3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle-viewmodel-navigation3" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-version" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-version" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-version" }

# Serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }

# Coroutines
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

# Ktor Client
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor-version" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-client-content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor-version" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-version" }

# Ktor Server
ktor-server-logback = { module = "ch.qos.logback:logback-classic", version.ref = "ktor-logback" }
ktor-serverCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor-version" }
ktor-serverTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor-version" }
ktor-server-content = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-server-postgresSql = { module = "org.postgresql:postgresql", version.ref = "ktor-postgres-sql-driver" }
ktor-server-hikari = { module = "com.zaxxer:HikariCP", version.ref = "ktor-hikari-cp" }
ktor-server-exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "ktor-exposed-orm" }
ktor-server-exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "ktor-exposed-orm" }
ktor-server-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "ktor-exposed-orm" }

ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor-server-auth" }

# Hashing
bcrypt-hashing = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
kotlin-mockk = {module = "io.mockk:mockk", version.ref = "mockk"  }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
androidx-room = { id = "androidx.room", version.ref = "room-version" }
